

#cd backend
#cd
#python -m uvicorn main:app --reload


players = [
    {"id": 1, "name": "Virat Kohli", "role": "Batsman", "base_price": 2},
    {"id": 2, "name": "Rohit Sharma", "role": "Batsman", "base_price": 2},
    {"id": 3, "name": "Jasprit Bumrah", "role": "Bowler", "base_price": 2},
    {"id": 4, "name": "Hardik Pandya", "role": "All-Rounder", "base_price": 2},
    {"id": 5, "name": "KL Rahul", "role": "Batsman", "base_price": 2},
    {"id": 6, "name": "Shubman Gill", "role": "Batsman", "base_price": 2},
    {"id": 7, "name": "Suryakumar Yadav", "role": "Batsman", "base_price": 2},
    {"id": 8, "name": "Rishabh Pant", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 9, "name": "Sanju Samson", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 10, "name": "Ishan Kishan", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 11, "name": "Ravindra Jadeja", "role": "All-Rounder", "base_price": 2},
    {"id": 12, "name": "Axar Patel", "role": "All-Rounder", "base_price": 2},
    {"id": 13, "name": "Shivam Dube", "role": "All-Rounder", "base_price": 2},
    {"id": 14, "name": "Washington Sundar", "role": "All-Rounder", "base_price": 2},
    {"id": 15, "name": "Glenn Maxwell", "role": "All-Rounder", "base_price": 2},
    {"id": 16, "name": "Mohammed Shami", "role": "Bowler", "base_price": 2},
    {"id": 17, "name": "Mohammed Siraj", "role": "Bowler", "base_price": 2},
    {"id": 18, "name": "Kuldeep Yadav", "role": "Bowler", "base_price": 2},
    {"id": 19, "name": "Yuzvendra Chahal", "role": "Bowler", "base_price": 2},
    {"id": 20, "name": "Arshdeep Singh", "role": "Bowler", "base_price": 2},
    {"id": 21, "name": "Babar Azam", "role": "Batsman", "base_price": 2},
    {"id": 22, "name": "Jos Buttler", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 23, "name": "David Warner", "role": "Batsman", "base_price": 2},
    {"id": 24, "name": "Steve Smith", "role": "Batsman", "base_price": 2},
    {"id": 25, "name": "Kane Williamson", "role": "Batsman", "base_price": 2},
    {"id": 26, "name": "Ben Stokes", "role": "All-Rounder", "base_price": 2},
    {"id": 27, "name": "Sam Curran", "role": "All-Rounder", "base_price": 2},
    {"id": 28, "name": "Marcus Stoinis", "role": "All-Rounder", "base_price": 2},
    {"id": 29, "name": "Andre Russell", "role": "All-Rounder", "base_price": 2},
    {"id": 30, "name": "Sunil Narine", "role": "All-Rounder", "base_price": 2},
    {"id": 31, "name": "Pat Cummins", "role": "Bowler", "base_price": 2},
    {"id": 32, "name": "Mitchell Starc", "role": "Bowler", "base_price": 2},
    {"id": 33, "name": "Trent Boult", "role": "Bowler", "base_price": 2},
    {"id": 34, "name": "Kagiso Rabada", "role": "Bowler", "base_price": 2},
    {"id": 35, "name": "Anrich Nortje", "role": "Bowler", "base_price": 2},
    {"id": 36, "name": "Rinku Singh", "role": "Batsman", "base_price": 2},
    {"id": 37, "name": "Yashasvi Jaiswal", "role": "Batsman", "base_price": 2},
    {"id": 38, "name": "Tilak Varma", "role": "Batsman", "base_price": 2},
    {"id": 39, "name": "Devon Conway", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 40, "name": "Quinton de Kock", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 41, "name": "Rahul Tripathi", "role": "Batsman", "base_price": 2},
    {"id": 42, "name": "Mayank Agarwal", "role": "Batsman", "base_price": 2},
    {"id": 43, "name": "Deepak Chahar", "role": "Bowler", "base_price": 2},
    {"id": 44, "name": "Bhuvneshwar Kumar", "role": "Bowler", "base_price": 2},
    {"id": 45, "name": "Umesh Yadav", "role": "Bowler", "base_price": 2},
    {"id": 46, "name": "Nicholas Pooran", "role": "Wicket-Keeper", "base_price": 2},
    {"id": 47, "name": "Shimron Hetmyer", "role": "Batsman", "base_price": 2},
    {"id": 48, "name": "Jason Holder", "role": "All-Rounder", "base_price": 2},
    {"id": 49, "name": "Chris Woakes", "role": "All-Rounder", "base_price": 2},
    {"id": 50, "name": "Liam Livingstone", "role": "All-Rounder", "base_price": 2},
    {"id": 51, "name": "Harshal Patel", "role": "Bowler", "base_price": 2},
    {"id": 52, "name": "Avesh Khan", "role": "Bowler", "base_price": 2},
    {"id": 53, "name": "Umran Malik", "role": "Bowler", "base_price": 2},
    {"id": 54, "name": "Prithvi Shaw", "role": "Batsman", "base_price": 2}
]
